# Generated by Django 2.1.2 on 2018-10-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork_image_processor', '0002_auto_20181007_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
    ]
