# Generated by Django 2.1.2 on 2018-10-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork_image_processor', '0003_auto_20181007_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='static/'),
        ),
    ]
