# Generated by Django 2.1.2 on 2018-10-16 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artwork_image_processor', '0003_auto_20181015_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageFile',
            field=models.ImageField(upload_to='image_uploads/'),
        ),
    ]
